### ISSUE TITLE
Final Check of the items in the checklists

### ISSUE THREAD

**Issue by mtaromi** [Ahmed-Sadeq-Hussein/Mjukvaruutvekling-grupp-5#68]

**Comment by hannankhalil** [comment]
workshop 5 created and been completed #69

**Comment by mtaromi** [comment]
@Ahmed-Sadeq-Hussein, @Baesar, @RamaTech03, @hannankhalil, and @SanaSu1

You completed the required items for the 'Laboratory Work' and received 4.5 credits.

Well done! 🎉

**Comment by RamaTech03** [comment]
[heart]         Rama Muharam reacted to your message:
________________________________
