### ISSUE TITLE
Agile Practices for workshop 5

### ISSUE THREAD

**Issue by RamaTech03** [Ahmed-Sadeq-Hussein/Mjukvaruutvekling-grupp-5#70]

**Comment by hannankhalil** [comment]
1. Responsibilities Assignment
Task Assignment: Specific units of code or features are assigned to individual team members. Clear specifications and requirements are provided for the assigned work, ensuring everyone understands their responsibilities.

2. Incremental Development
Feature Implementation: Features are implemented in small, incremental steps. This includes continuous testing and bug-fixing of the code until it is ready for delivery, promoting a stable and reliable development process.

3. Customer Collaboration
Close Collaboration: The team works closely with the customer to understand their requirements. An example is the request for save file functionality. Customer feedback is actively incorporated into the development process, ensuring the final product meets their needs and expectations.

4. Kanban Board
Progress Tracking: A weekly Kanban board is used to track current progress and tasks. Regular discussions are held to review the board, addressing any blockers or issues that arise, and ensuring smooth workflow management.  
                
5. Continuous Integration/Continuous Deployment (CI/CD)
 Frequent integration of code into a shared repository, followed by automated testing and deployment. This helps detect and address issues early, ensuring a more reliable and faster release process.

**Comment by hannankhalil** [comment]
1. Responsibilities Assignment
Task Assignment: Specific units of code or features are assigned to individual team members. Clear specifications and requirements are provided for the assigned work, ensuring everyone understands their responsibilities.

2. Incremental Development
Feature Implementation: Features are implemented in small, incremental steps. This includes continuous testing and bug-fixing of the code until it is ready for delivery, promoting a stable and reliable development process.

3. Customer Collaboration
Close Collaboration: The team works closely with the customer to understand their requirements. An example is the request for save file functionality. Customer feedback is actively incorporated into the development process, ensuring the final product meets their needs and expectations.

4. Kanban Board
Progress Tracking: A weekly Kanban board is used to track current progress and tasks. Regular discussions are held to review the board, addressing any blockers or issues that arise, and ensuring smooth workflow management. 
                 
5. Continuous Integration/Continuous Deployment (CI/CD)
 Frequent integration of code into a shared repository, followed by automated testing and deployment. This helps detect and address issues early, ensuring a more reliable and faster release process.
